version: "3.8"

services:
  backend:
    build:
      context: .
      target: prod
    environment:
      DATABASE_URL: ${DATABASE_URL}
    ports:
      - 3000:3000
    depends_on:
      - db

  db:
    image: postgres:12-alpine
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - 5432:5432

  redocly:
    image: redocly/redoc
    environment:
      SPEC_URL: ${REDOCLY_SPEC_URL}
    ports:
      - 5050:80
